# -*- coding: utf-8 -*-
"""Sana_PriceOptima.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AsG1zGSaTNqxrimV6tpql83QkAealBiP
"""

import pandas as pd
import numpy as np
from IPython.display import display
dataset= pd.read_csv('dynamic_pricing (1).csv')
dataset.head()

dataset.head()

dataset.isnull().sum()

dataset.describe()

dataset.shape

dataset.columns.tolist()

dataset.nunique()

dataset.info()

print("Duplicates:", dataset.duplicated().sum())
dataset = dataset.drop_duplicates()

#Handling missing values
for col in dataset.columns:
    if dataset[col].dtype in ['int64', 'float64']:   # numeric
        dataset[col] = dataset[col].fillna(dataset[col].median())
    else:                                            # categorical
        dataset[col] = dataset[col].fillna(dataset[col].mode()[0])
print("Missing values per column after preprocessing:")
print(dataset.isnull().sum())

print(dataset.head())

import numpy as np

# Function to detect outliers using IQR
def find_outliers_iqr(data, col):
    Q1 = data[col].quantile(0.25)   # 25th percentile
    Q3 = data[col].quantile(0.75)   # 75th percentile
    IQR = Q3 - Q1                   # Interquartile range

    lower = Q1 - 1.5 * IQR           # Lower bound
    upper = Q3 + 1.5 * IQR           # Upper bound

    # Outliers are those outside the bounds
    outliers = data[(data[col] < lower) | (data[col] > upper)]

    return outliers, lower, upper

# Apply to all numerical columns
numeric_cols = dataset.select_dtypes(include=[np.number]).columns

for col in numeric_cols:
    outliers, lower, upper = find_outliers_iqr(dataset, col)
    print(f"\nColumn: {col}")
    print(f"Lower Bound: {lower}, Upper Bound: {upper}")
    print(f"Number of Outliers: {len(outliers)}")

    # Show example outlier values
    if not outliers.empty:
        print("Example Outliers:\n", outliers[[col]].head())

import matplotlib.pyplot as plt
import numpy as np

# Function to detect and plot outliers
def plot_outliers_with_iqr(data, col):
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    # Detect outliers
    outliers = data[(data[col] < lower) | (data[col] > upper)]

    # Plot
    plt.figure(figsize=(8, 4))
    plt.scatter(data.index, data[col], color='yellow', label='Data Points')

    # Outlier bounds
    plt.axhline(y=lower, color='red', linestyle='--', label=f'Lower Bound ({lower:.2f})')
    plt.axhline(y=upper, color='green', linestyle='--', label=f'Upper Bound ({upper:.2f})')

    plt.title(f"Outlier Detection in {col}")
    plt.xlabel("Index")
    plt.ylabel(col)
    plt.legend()
    plt.show()

# Apply to all numeric columns
for col in dataset.select_dtypes(include=np.number).columns:
    plot_outliers_with_iqr(dataset, col)

import pandas as pd
import numpy as np
dataset = pd.read_csv("/content/drive/MyDrive/dynamic_pricing.csv")

#Assumptions
# Completed rides = min(Riders, Drivers)
dataset["Completed_Rides"] = dataset[["Number_of_Riders", "Number_of_Drivers"]].min(axis=1)

# Cost assumption (70% of historical cost = driver payout + fuel + fees)
dataset["Cost_per_Ride"] = 0.7 * dataset["Historical_Cost_of_Ride"]

# Recommended Price (scenario: +10% increase)
dataset["Recommended_Price"] = dataset["Historical_Cost_of_Ride"] * 1.10

# 1.Revenue
baseline_revenue = (dataset["Historical_Cost_of_Ride"] * dataset["Completed_Rides"]).sum()
recommended_revenue = (dataset["Recommended_Price"] * dataset["Completed_Rides"]).sum()
dataset["Revenue"] = dataset["Historical_Cost_of_Ride"] * dataset["Completed_Rides"]

# 2.Profit
dataset["Profit"] = (dataset["Historical_Cost_of_Ride"] - dataset["Cost_per_Ride"]) * dataset["Completed_Rides"]

# 3.Revenue Lift (%)
Revenue_lift = ((recommended_revenue - baseline_revenue) / baseline_revenue) * 100
if baseline_revenue == 0:
    Revenue_lift = np.nan

# 4.Gross Margin (%)
Gross_margin = (dataset["Profit"].sum() / baseline_revenue) * 100

# 5.Conversion Rate (%)
total_riders = dataset["Number_of_Riders"].sum()
total_completed = dataset["Completed_Rides"].sum()
Conversion_rate = (total_completed / total_riders) * 100 if total_riders > 0 else np.nan

# 6.Price Change Rate (%)
dataset["Price_Change_%"] = dataset["Historical_Cost_of_Ride"].pct_change().abs() * 100
dataset["Price_Change_%"] = dataset["Price_Change_%"].fillna(0)
Price_change_rate = dataset["Price_Change_%"].mean()

# 7.Cancellation Rate (%)
dataset["Cancellation_Rate_%"] = ((dataset["Number_of_Riders"] - dataset["Completed_Rides"]) / dataset["Number_of_Riders"]) * 100
Cancellation_rate = dataset["Cancellation_Rate_%"].mean()

results = {
    "Revenue (Baseline)": round(baseline_revenue, 2),
    "Revenue (Scenario +10% Price)": round(recommended_revenue, 2),
    "Revenue Lift %": round(Revenue_lift, 2),
    "Profit Total": round(dataset["Profit"].sum(), 2),
    "Gross Margin %": round(Gross_margin, 2),
    "Conversion Rate %": round(Conversion_rate, 2),
    "Avg Price Change %": round(Price_change_rate, 2),
    "Cancellation Rate %": round(Cancellation_rate, 2),
}
print("Aggregate KPI Summary")
for k, v in results.items():
    print(f"{k}: {v}")

dataset.shape

dataset.head()

# --- Feature Engineering ---
import numpy as np
import pandas as pd

# 1. Supply, Demand, and Inventory Ratios
dataset['Rider_Driver_Ratio'] = dataset['Number_of_Riders'] / dataset['Number_of_Drivers']
dataset['Driver_to_Rider_Ratio'] = dataset['Number_of_Drivers'] / dataset['Number_of_Riders']
dataset['Supply_Tightness'] = dataset['Number_of_Riders'] / dataset['Number_of_Drivers']
dataset['Inventory_Health_Index'] = dataset['Number_of_Drivers'] / dataset['Number_of_Riders']

# 2. Probability of Ride Completion (p_complete)
dataset['p_complete'] = np.minimum(1.0, dataset['Driver_to_Rider_Ratio'])

# 3. Cost per Minute
dataset['Cost_per_Min'] = dataset['Historical_Cost_of_Ride'] / dataset['Expected_Ride_Duration']

# 4. Numerical Feature Mapping
# Loyalty Score based on customer status
loyalty_mapping = {'Gold': 3, 'Silver': 2, 'Regular': 1}
dataset['Loyalty_Score'] = dataset['Customer_Loyalty_Status'].map(loyalty_mapping)

# Vehicle Factor based on vehicle type
vehicle_mapping = {'Premium': 1.5, 'Economy': 1.0}
dataset['Vehicle_Factor'] = dataset['Vehicle_Type'].map(vehicle_mapping)

# 5. Peak Time Indicator
peak_times = ['Evening', 'Night']
dataset['Peak'] = dataset['Time_of_Booking'].apply(lambda x: 1 if x in peak_times else 0)

# 6. Competitor Pricing
np.random.seed(42)
random_factor = np.random.uniform(0.9, 1.1, size=len(dataset))
dataset['competitor_price'] = dataset['Historical_Cost_of_Ride'] * random_factor

# Competitor Price Index
dataset['Competitor_Price_Index'] = dataset['Historical_Cost_of_Ride'] / dataset['competitor_price']

# 7. Baseline Price and Target Variable
dataset['baseline_price'] = dataset['Historical_Cost_of_Ride']
dataset['price'] = dataset['Historical_Cost_of_Ride']

print("DataFrame with Engineered Features:")
display(dataset[['Rider_Driver_Ratio','Driver_to_Rider_Ratio','Inventory_Health_Index', 'Loyalty_Score', 'Cost_per_Min', 'Peak','Supply_Tightness', 'Vehicle_Factor','baseline_price','competitor_price','Competitor_Price_Index','p_complete', 'price']].head())

#Numeric Distributions
import matplotlib.pyplot as plt
import seaborn as sns

num_cols = dataset.select_dtypes(include='number').columns
plt.figure(figsize=(15, 5 * len(num_cols)))
for i, col in enumerate(num_cols, 1):
    plt.subplot(len(num_cols), 1, i)
    sns.histplot(dataset[col], kde=True, bins=30, color='skyblue')
    plt.title(f"Distribution of {col}")
plt.tight_layout()
plt.show()

# Boxplots for Outlier View
plt.figure(figsize=(15, 5 * ((len(num_cols)+1)//2)))

for i, col in enumerate(num_cols, 1):
    plt.subplot((len(num_cols)+1)//2, 2, i)  # 2 plots per row
    sns.boxplot(x=dataset[col], color='lightcoral')
    plt.title(f"Boxplot of {col}")
    plt.xlabel(col)

plt.tight_layout()
plt.show()

#Categorical Counts
cat_cols = dataset.select_dtypes(exclude=['number']).columns

plt.figure(figsize=(15, 10))
for i, col in enumerate(cat_cols, 1):
    plt.subplot(len(cat_cols)//2 + 1, 2, i)
    sns.countplot(data=dataset, x=col, hue=col, palette='viridis', legend=False)
    plt.title(f"Count of {col}")
    plt.xticks(rotation=30)
plt.tight_layout()
plt.show()

# Relationship between Number of Riders and Number of Drivers
plt.figure(figsize=(8,6))
sns.scatterplot(
    data=dataset,
    x="Number_of_Riders",
    y="Number_of_Drivers",
    alpha=0.6,
    color="teal"
)
sns.regplot(
    data=dataset,
    x="Number_of_Riders",
    y="Number_of_Drivers",
    scatter=False,
    color="red"
)
plt.title("Relationship between Number of Riders and Number of Drivers")
plt.xlabel("Number of Riders")
plt.ylabel("Number of Drivers")
plt.show()

#Conversion by Segments (using p_complete)
plt.figure(figsize=(15, 8))

for i, col in enumerate(['Customer_Loyalty_Status','Vehicle_Type','Time_of_Booking'], 1):
    plt.subplot(2, 2, i)
    sns.barplot(
        x=col,
        y='p_complete',
        data=dataset,
        hue=col,
        palette='coolwarm',
        legend=False,
        errorbar=None
    )
    plt.title(f"Conversion (p_complete) by {col}")
    plt.xticks(rotation=30)

plt.tight_layout()
plt.show()

#Correlation Heatmap (Key Engineered Features)
plt.figure(figsize=(12, 8))
engineered_cols = [
    'Competitor_Price_Index','Cost_per_Min','Driver_to_Rider_Ratio',
    'Inventory_Health_Index','Loyalty_Score','Peak','Rider_Driver_Ratio',
    'Supply_Tightness','Vehicle_Factor','baseline_price','competitor_price',
    'p_complete','price'
]
corr = dataset[engineered_cols].corr()

sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title("Correlation Heatmap of Engineered Features")
plt.show()

import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# 5.1 Seasonality: Conversion & Price by Time Buckets
seasonality = (
    dataset.groupby("Time_of_Booking")
        .agg(
            mean_conv=("p_complete", "mean"),
            mean_price=("price", "mean"),
            total_intents=("Number_of_Riders", "sum")
        )
        .sort_values("mean_conv", ascending=False)
)
print("Seasonality Analysis")
display(seasonality)
# Plotting conversion rate by time of day
seasonality["mean_conv"].plot(kind="bar", title="Mean Conversion Rate by Time of Booking")
plt.ylabel("Mean Conversion Rate (p_complete)")
plt.show()

# 5.2 Competitor Pressure: Price Gap & Index
dataset["Competitor_Gap_pct"] = (dataset["price"] - dataset["competitor_price"]) / dataset["competitor_price"] * 100.0
comp_pressure = (
    dataset.groupby("Vehicle_Type")
        .agg(
            avg_gap_pct=("Competitor_Gap_pct", "mean"),
            mean_comp_price=("competitor_price", "mean"),
            mean_our_price=("price", "mean"),
        )
        .sort_values("avg_gap_pct")
)
print("\nCompetitor Pressure Analysis")
display(comp_pressure)

# 5.3 Inventory Health Bands & Conversion
bins = [0, 0.5, 0.8, 1.2, 10]
labels = ["Very Tight", "Tight", "Balanced", "Loose"]

dataset["Inventory_Band"] = pd.cut(dataset["Driver_to_Rider_Ratio"], bins=bins, labels=labels, include_lowest=True)

inv_summary = dataset.groupby("Inventory_Band", observed=True).agg(
    mean_conv=("p_complete", "mean"),
    mean_price=("price", "mean"),
    count=("Inventory_Band", "size")
)
print("Inventory Health Analysis")
display(inv_summary)
# Plotting conversion rate by inventory band
inv_summary["mean_conv"].plot(kind="bar", title="Mean Conversion by Inventory Band")
plt.ylabel("Mean Conversion Rate (p_complete)")
plt.show()

# 6. Customer Segmentation (KMeans)
seg_features = [
    "Loyalty_Score", "Rider_Driver_Ratio", "Driver_to_Rider_Ratio",
    "Supply_Tightness", "Cost_per_Min", "Inventory_Health_Index",
    "Expected_Ride_Duration"
]
X = dataset[seg_features].copy().fillna(dataset[seg_features].median())
scaler = StandardScaler()
Xs = scaler.fit_transform(X)

kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
dataset["segment_k4"] = kmeans.fit_predict(Xs)

seg_profile = (
    dataset.groupby("segment_k4")
        .agg(
            mean_conv=("p_complete", "mean"),
            mean_price=("price", "mean"),
            mean_cost=("Historical_Cost_of_Ride", "mean"),
            mean_loyalty=("Loyalty_Score", "mean"),
            mean_ratio=("Rider_Driver_Ratio", "mean"),
            count=("segment_k4", "size")
        )
        .sort_values("mean_conv", ascending=False)
)
print("\nCustomer Segmentation Profile")
display(seg_profile)

dataset.shape

dataset.head()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display

#Baseline Pricing Engine
# --- Prerequisite: Create Inventory Health Bands ---
bins = [0, 0.5, 0.8, 1.2, 10]
labels = ["Very Tight", "Tight", "Balanced", "Loose"]
dataset["Inventory_Band"] = pd.cut(dataset["Driver_to_Rider_Ratio"], bins=bins, labels=labels, include_lowest=True)

def get_baseline_price_recommendation(row):
    peak_times = ['Evening', 'Night', 'Morning']
    time_of_day = row['Time_of_Booking']

    if time_of_day in peak_times:
        base_price = row['Historical_Cost_of_Ride']

        if time_of_day in ['Evening', 'Night']:
            base_price *= 1.15
        elif time_of_day == 'Morning':
            base_price *= 1.10

        inventory_band = row['Inventory_Band']
        if inventory_band == 'Very Tight':
            base_price *= 1.20
        elif inventory_band == 'Tight':
            base_price *= 1.10
        elif inventory_band == 'Loose':
            base_price *= 0.90

        return base_price
    else:
        return row['Historical_Cost_of_Ride']

STABILITY_PERCENT = 0.15
MIN_GROSS_MARGIN_PERCENT = 0.12

def audit_policy_rules(df_original, df_scenario):
    print("\n--- Policy Audit Results ---")
    audit_df = df_scenario.copy()

    cost = audit_df['Historical_Cost_of_Ride'] * 0.7
    audit_df['gm_baseline'] = (audit_df['Historical_Cost_of_Ride'] - cost) / audit_df['Historical_Cost_of_Ride']
    audit_df['gm_scenario'] = (audit_df['baseline_recommended_price'] - cost) / audit_df['baseline_recommended_price']

    rules = {
        'stab_ok': audit_df['baseline_recommended_price'].between(
            audit_df['Historical_Cost_of_Ride'] * (1 - STABILITY_PERCENT),
            audit_df['Historical_Cost_of_Ride'] * (1 + STABILITY_PERCENT)
        ),
        'gm12_ok': audit_df['gm_scenario'] >= MIN_GROSS_MARGIN_PERCENT,
        'gm_base_ok': audit_df['gm_scenario'] >= audit_df['gm_baseline'],
        'cancel_ok': audit_df['p_complete'] >= df_original['p_complete'] # Checks if p_complete decreased
    }

    for rule_name, result_series in rules.items():
        print(f"{rule_name.replace('_', ' ').title()}: {result_series.all()}")
        audit_df[rule_name] = result_series

    audit_df['all_ok'] = audit_df[rules.keys()].all(axis=1)
    violating_rows = audit_df[~audit_df['all_ok']]

    if not violating_rows.empty:
        print(f"\nFound {len(violating_rows)} violating rows (showing up to 10):")
        display(violating_rows[['stab_ok', 'gm12_ok', 'gm_base_ok', 'cancel_ok', 'all_ok']].head(10))
    else:
        print("\nNo policy violations found.")
    return

def evaluate_performance(df_original, df_scenario):
    results = {}
    for name, df in [('Baseline', df_original), ('Scenario', df_scenario)]:
        # Use a consistent price column name for calculation
        price_col = 'Historical_Cost_of_Ride' if name == 'Baseline' else 'baseline_recommended_price'
        bookings = df['Number_of_Riders']
        revenue = (df[price_col] * bookings).sum()
        cost = (df['Historical_Cost_of_Ride'] * 0.7 * bookings).sum()
        profit = revenue - cost
        results[f'Revenue ({name})'] = revenue
        results[f'Gross Margin ({name}) %'] = (profit / revenue) * 100 if revenue else 0
        results[f'Cancellation Rate ({name}) %'] = 100 - (df['p_complete'] * 100).mean() # Based on p_complete

    results['Revenue Lift (%)'] = (results['Revenue (Scenario)'] - results['Revenue (Baseline)']) / results['Revenue (Baseline)'] * 100

    print("\n--- FINAL KPIs (Scenario vs Baseline) ---")
    for key, value in results.items():
        print(f"{key}: {value:,.2f}")
    return

# Main Execution and Analysis
dataset['baseline_recommended_price'] = dataset.apply(get_baseline_price_recommendation, axis=1)

df_scenario = dataset.copy()
df_scenario['price'] = df_scenario['baseline_recommended_price']

evaluate_performance(dataset, df_scenario)

audit_policy_rules(dataset, df_scenario)

print("\nSample (top 10) of baseline vs recommended:")
comparison_sample = dataset[[
    'Vehicle_Type', 'Time_of_Booking', 'Location_Category', 'Customer_Loyalty_Status',
    'Number_of_Riders', 'Number_of_Drivers', 'Driver_to_Rider_Ratio', 'Historical_Cost_of_Ride',
    'baseline_recommended_price'
]].copy()
display(comparison_sample.head(10))

import pandas as pd
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant

features = [
    'Number_of_Riders', 'Number_of_Drivers', 'Number_of_Past_Rides',
    'Average_Ratings', 'Expected_Ride_Duration', 'Historical_Cost_of_Ride',
    'Location_Category', 'Customer_Loyalty_Status', 'Time_of_Booking', 'Vehicle_Type'
]

df_for_vif = dataset[features].dropna()

#One-Hot Encode the categorical features.
df_vif_encoded = pd.get_dummies(df_for_vif, drop_first=True, dtype=float)

X = add_constant(df_vif_encoded)

vif_data = pd.DataFrame()
vif_data["feature"] = X.columns[1:]
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(1, X.shape[1])]

print("--- VIF for Selected Features ---")
vif_sorted = vif_data.sort_values('VIF', ascending=False)
display(vif_sorted)

import pandas as pd
import numpy as np
import joblib
import warnings
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from IPython.display import display
warnings.filterwarnings("ignore")

# Define the features (X) and target (y)
# The target is the probability of ride completion
y = dataset['p_complete'].clip(0, 1)

feature_columns = [
    "baseline_price",
    "Expected_Ride_Duration", "Number_of_Riders", "Number_of_Drivers",
    "Rider_Driver_Ratio", "Cost_per_Min", "competitor_price",
    "Time_of_Booking", "Location_Category", "Vehicle_Type", "Customer_Loyalty_Status"
]
X = dataset[feature_columns]

# Splitting data into training and testing sets for backtesting
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Preprocessing Pipeline(Scaling & Encoding)
categorical_features = X.select_dtypes(include=['object', 'category']).columns
numerical_features = X.select_dtypes(include=np.number).columns

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ])

#Training and evaluation od models
models = {
    "DecisionTree": DecisionTreeRegressor(max_depth=10, min_samples_leaf=10, random_state=42),
    "RandomForest": RandomForestRegressor(n_estimators=100, max_depth=10, min_samples_leaf=10, random_state=42, n_jobs=-1),
    "GradientBoosting": GradientBoostingRegressor(learning_rate=0.05, n_estimators=200, max_depth=3, random_state=42),
    "XGBoost": XGBRegressor(n_estimators=200, learning_rate=0.05, max_depth=5, random_state=42, n_jobs=-1)
}
results = {}
fitted_pipelines = {}

for name, model in models.items():
    pipe = Pipeline(steps=[('preprocessor', preprocessor), ('model', model)])
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test).clip(0, 1)

    # Evaluation metrics
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    # Perform cross-validation to get a more stable performance estimate
    cv_scores = cross_val_score(pipe, X_train, y_train, cv=5, scoring='neg_root_mean_squared_error', n_jobs=-1)
    cv_rmse = -np.mean(cv_scores)

    results[name] = {"RMSE": rmse, "MAE": mae,"MSE": mse, "R2": r2, "cv_RMSE": cv_rmse}
    fitted_pipelines[name] = pipe

results_df = pd.DataFrame(results).T.sort_values(by="RMSE")
format_dict = {
        'RMSE': '{:.6f}',
        'MAE': '{:.6f}',
        'MSE': '{:.6f}',
        'R2': '{:.4f}',
        'CV_RMSE': '{:.6f}'
    }
    # Apply the formatting to the DataFrame for display
display(results_df.style.format(format_dict))


# Select the best model based on the lowest RMSE
best_model_name = results_df.index[0]
best_model_pipeline = fitted_pipelines[best_model_name]
print(f"\nSelected best model: {best_model_name}")

# =======================================================
# Step 4: Backtest a Pricing Policy Using the Best Model
# =======================================================
print("\n--- Backtesting optimal pricing policy on the test set ---")

def find_optimal_price(row, model_pipeline, price_grid_size=20):
    """
    For a given ride, search across a range of prices to find the one
    that maximizes expected revenue (price * predicted_p_complete).
    """
    base_price = row['baseline_price']

    # Create a grid of candidate prices around the baseline
    price_grid = np.linspace(base_price * 0.85, base_price * 1.15, price_grid_size)

    # Create a DataFrame for all price candidates
    test_scenarios = pd.DataFrame([row] * price_grid_size)
    test_scenarios['baseline_price'] = price_grid # Use baseline_price as the dynamic price feature

    # Predict p_complete for all candidate prices at once
    predicted_p_completes = model_pipeline.predict(test_scenarios).clip(0, 1)

    # Calculate expected revenue for each price
    expected_revenues = price_grid * predicted_p_completes

    # Find the price that gives the maximum expected revenue
    optimal_price = price_grid[np.argmax(expected_revenues)]

    return optimal_price

# Apply the policy to every row in the test set to get recommended prices
X_test_copy = X_test.copy()
X_test_copy['recommended_price'] = X_test_copy.apply(
    lambda row: find_optimal_price(row, best_model_pipeline),
    axis=1
)

# =======================================================
# Step 5: Evaluate Final KPIs and Save the Model
# =======================================================

# Function to calculate final business KPIs
def calculate_final_kpis(test_df_with_recs):
    # Baseline revenue assumes every rider books at the original price
    baseline_revenue = (test_df_with_recs['baseline_price'] * test_df_with_recs['Number_of_Riders']).sum()

    # Scenario revenue uses the newly recommended prices
    scenario_revenue = (test_df_with_recs['recommended_price'] * test_df_with_recs['Number_of_Riders']).sum()

    revenue_lift = (scenario_revenue - baseline_revenue) / baseline_revenue * 100

    kpis = {
        "Revenue (Baseline)": f"${baseline_revenue:,.2f}",
        "Revenue (Scenario)": f"${scenario_revenue:,.2f}",
        "Revenue Lift (%)": f"{revenue_lift:.2f}%"
    }
    return kpis

# Calculate and print the final business impact
final_kpis = calculate_final_kpis(X_test_copy)
print("\n--- FINAL KPIs (Scenario vs Baseline on Test Set) ---")
for k, v in final_kpis.items():
    print(f"{k}: {v}")

# Save the best model pipeline to disk using joblib
model_filename = "best_pricing_demand_model.joblib"
joblib.dump(best_model_pipeline, model_filename)
print(f"\nBest model pipeline saved to: '{model_filename}'")